Repository CA-G12/Bakeza-Shams, pull requests merged in 2023-02, with the labels that each got.

#2 add git workshop heading & shadow styling
  index.html
  style.css
Labels: waiting review, approved

#5 Fix typo in page heading
  index.html
Labels: waiting review

#6 change class heading
  index.html
Labels: approved
